name: 'Forum One - Canvas'
description: 'Provides default baseline configuration for all standard Drupal build projects.'
type: 'Site'

recipes:
  - drupal_base

install:
  - address
  - better_exposed_filters
  - components
  - csp
  - decorative_image_widget
  - devel
  - diff
  - exif_orientation
  - facets
  - fakeobjects
  - focal_point
  - gesso
  - gesso_helper
  - google_tag
  - login_history
  - maxlength
  - media_library_edit
  - rabbit_hole
  - redirect
  - search_api
  - seckit
  - select2
  - simple_sitemap
  - stage_file_proxy
  - twig_field_value
  - twig_tweak
  - username_enumeration_prevention
  - webform

config:
  strict: false
  import:
    # We really only want the view, but apparently block_content expects the field storage to always exist. See @link https://www.drupal.org/project/drupal/issues/3447617
    block_content:
      - 'field.storage.block_content.body'
      - 'views.view.block_content'
    redirect: '*'
    user:
      # Bring in the admin view for users.
      - 'views.view.user_admin_people'
    webform: '*'
  actions:
    # Set default timezone to New York and prevent users from changing their own timezones.
    system.date:
      simpleConfigUpdate:
        timezone.default: 'America/New_York'
        timezone.user.configurable: false
    # Ensure gesso is the default theme.
    system.theme:
      simple_config_update:
        default: 'gesso'
    # Temporary until https://github.com/forumone/gesso/pull/924 is merged.
    block.block.gesso_tools:
      simple_config_update:
        settings.label_display: false
